import React, { useState } from "react";
import { Link } from "react-router-dom";
import { data } from "../website/data/gaming/gamingData";

const Gaming = () => {
  const [games, setGames] = useState(data);
  return (
    <>
      <section className="youtube-clone-gaming-poster">
        <h1>New Mobile Legends Launch</h1>
        <p>game channel</p>
      </section>
      <section className="gaming-suscribe-sec">
        <div className="gaming-suscribe">
          <img
            src="https://yt3.ggpht.com/B0BHdmM16wG0nekse9AVX-78swbkdqWJzx9ORKuYRgxMJbC7Oaq1qD7bKWrhL2w4vM5ImqdoVw=s88-c-k-c0x00ffffff-no-rj-mo"
            alt=""
          />
          <article>
            <h1>Gaming</h1>
            <p>94M Subscribers</p>
          </article>
        </div>
        <button>suscribe</button>
      </section>
      <TopGames games={games} />
    </>
  );
};

let TopGames = ({ games }) => {
  return (
    <>
      <section className="youtube-clone-top-games">
        <article>
          <h2>Top Live Games</h2>
          <p>Auto Generated by YouTube</p>
        </article>
        <Link to="/">View All</Link>
      </section>

      <div className="topgames-row">
        {games.first.map((item) => {
          return (
            <div className="topgames-frame">
              <img src={item.img} alt="" />

              <h1>{item.title}</h1>
              <p>{item.name}</p>
            </div>
          );
        })}
      </div>
    </>
  );
};

export default Gaming;
